# Generated by Django 3.2 on 2021-04-10 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('FHD_link', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('HD_link', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('SD_link', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('FHD_size', models.IntegerField(blank=True)),
                ('HD_size', models.IntegerField(blank=True)),
                ('SD_size', models.IntegerField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('synopsis', models.TextField(blank=True)),
                ('movie_id', models.CharField(blank=True, max_length=255)),
                ('back_drop', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
