# Generated by Django 3.2 on 2021-04-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
