# Generated by Django 3.2 on 2021-04-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedl', '0003_auto_20210411_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='FHD_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='HD_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='SD_size',
            field=models.BigIntegerField(null=True),
        ),
    ]
