# Generated by Django 3.2 on 2021-04-11 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedl', '0004_auto_20210411_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='UHD_link',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='movie',
            name='UHD_size',
            field=models.BigIntegerField(null=True),
        ),
    ]
