# Generated by Django 3.2 on 2021-04-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedl', '0005_auto_20210411_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.TextField(blank=True),
        ),
    ]
