# Generated by Django 3.2 on 2021-04-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedl', '0006_movie_original_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='back_drop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
