# Generated by Django 3.2 on 2021-04-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedl', '0007_auto_20210411_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
